### ISSUE TITLE
Getting Error while creating a course

### ISSUE THREAD

**Issue by Sreelekha7** [chvnaveenkumar/Codeword-GDPII#2]
When we enter the course details and click on Create course, it gives an error saying " There was duplicate course error". When we click on create course, the button is not working. The window stays on the screen and nothing happens. When clicked on the Create course button twice, the window disappears and the error pops up. After refreshing the page, the created course appears on the screen.

**Comment by SRAVYAKANCHARLA** [comment]
Completed Errors
